# Generated by Django 3.0.5 on 2020-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('Accomodation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('ID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64)),
                ('Cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('loggedin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('Name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('Accomodation', models.BooleanField()),
                ('Cart', models.ManyToManyField(blank=True, to='users.Cart')),
                ('Events', models.ManyToManyField(blank=True, to='users.Event')),
            ],
        ),
        migrations.CreateModel(
            name='notRegistered',
            fields=[
                ('Name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('Accomodation', models.BooleanField()),
                ('Events', models.ManyToManyField(blank=True, to='users.Event')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='Events',
            field=models.ManyToManyField(blank=True, to='users.Event'),
        ),
    ]
