# Generated by Django 3.0.5 on 2020-05-03 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('ID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64)),
                ('Cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SelectedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Events', models.ManyToManyField(blank=True, to='users.Event')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
