# Generated by Django 3.0.5 on 2020-05-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('Name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('Accomodation', models.BooleanField()),
                ('Events', models.ManyToManyField(blank=True, to='users.Event')),
            ],
        ),
    ]
